services:
  api:
    build: ./app
    container_name: FastApp
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --workers 2 --reload
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
